from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from .geometry import Stroke, plot_bounds_for_crop, total_path_length
from .printer import load_printer_profile
from .settings import CropBox, PlotterSettings


@dataclass
class GCodeSummary:
    output_path: Path
    stroke_count: int
    segment_count: int
    travel_count: int
    plot_bounds: CropBox
    draw_length_mm: float


def generate_gcode(
    source_path: Path,
    strokes: list[Stroke],
    crop: CropBox,
    settings: PlotterSettings,
    output_path: Path,
) -> GCodeSummary:
    settings.validate()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    pen_down_z = settings.home_z
    pen_up_z = settings.home_z + settings.z_hop
    safe_z = settings.home_z + settings.z_safe_height
    z_move_feed = settings.travel_feed
    travel_count = 0
    crop_outlines = _crop_outline_strokes(crop, settings)
    crop_outline_feed = settings.bounding_box_feed
    printer = load_printer_profile()

    lines.extend(
        [
            ";FLAVOR:Marlin",
            "; Generated by pen_plotter",
            f"; Source: {source_path.name}",
            f"; Generated: {datetime.now().isoformat(timespec='seconds')}",
            "; Target: Creality Ender-3 Pro pen plotter",
            "; No extrusion. No hotend or bed heating.",
            "G21 ; set units to millimeters",
            "G90 ; absolute positioning",
            "M104 S0 ; ensure hotend is off",
            "M140 S0 ; ensure bed is off",
            "M107 ; fan off",
            "G28 ; home all axes",
            f"G0 Z{_fmt(safe_z)} F{_fmt(z_move_feed)} ; safe Z before plotting",
        ]
    )

    for pass_index, crop_outline in enumerate(crop_outlines, start=1):
        travel_count += 1
        offset = (pass_index - 1) * settings.bounding_box_offset
        outline_pen_up_z = safe_z if pass_index == 1 else pen_up_z
        _append_stroke(
            lines=lines,
            stroke=crop_outline,
            label=(
                "Selected crop box outline "
                f"{pass_index}/{settings.bounding_box_repeat} "
                f"(+{_fmt(offset)} mm)"
            ),
            pen_down_z=pen_down_z,
            pen_up_z=outline_pen_up_z,
            travel_feed=settings.travel_feed,
            draw_feed=crop_outline_feed,
            z_move_feed=z_move_feed,
        )
    if crop_outlines:
        lines.append(f"G0 Z{_fmt(pen_up_z)} F{_fmt(z_move_feed)} ; pen up after crop outlines")

    for index, stroke in enumerate(strokes, start=1):
        if len(stroke) < 2:
            continue
        start = stroke[0]
        travel_count += 1
        lines.extend(
            [
                f"; Stroke {index}",
                f"G0 Z{_fmt(pen_up_z)} F{_fmt(z_move_feed)}",
                f"G0 X{_fmt(start[0])} Y{_fmt(start[1])} F{_fmt(settings.travel_feed)}",
                f"G1 Z{_fmt(pen_down_z)} F{_fmt(z_move_feed)} ; pen down",
            ]
        )
        for x, y in stroke[1:]:
            lines.append(
                f"G1 X{_fmt(x)} Y{_fmt(y)} F{_fmt(settings.draw_feed)}"
            )

    lines.extend(
        [
            f"G0 Z{_fmt(safe_z)} F{_fmt(z_move_feed)} ; safe Z before present move",
            f"G0 X0 Y{_fmt(printer.boundary_y)} F{_fmt(settings.travel_feed)} ; move to top left",
            "M104 S0 ; hotend off",
            "M140 S0 ; bed off",
            "M107 ; fan off",
            "M84 ; disable steppers",
            "; End of pen-plotter G-code",
            "",
        ]
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")

    return GCodeSummary(
        output_path=output_path,
        stroke_count=len(strokes),
        segment_count=sum(max(0, len(stroke) - 1) for stroke in strokes),
        travel_count=travel_count,
        plot_bounds=plot_bounds_including_preflight(crop, settings),
        draw_length_mm=total_path_length(strokes),
    )


def _append_stroke(
    lines: list[str],
    stroke: Stroke,
    label: str,
    pen_down_z: float,
    pen_up_z: float,
    travel_feed: float,
    draw_feed: float,
    z_move_feed: float,
) -> None:
    if len(stroke) < 2:
        return

    start = stroke[0]
    lines.extend(
        [
            f"; {label}",
            f"G0 Z{_fmt(pen_up_z)} F{_fmt(z_move_feed)}",
            f"G0 X{_fmt(start[0])} Y{_fmt(start[1])} F{_fmt(travel_feed)}",
            f"G1 Z{_fmt(pen_down_z)} F{_fmt(z_move_feed)} ; pen down",
        ]
    )
    for x, y in stroke[1:]:
        lines.append(f"G1 X{_fmt(x)} Y{_fmt(y)} F{_fmt(draw_feed)}")


def plot_bounds_including_preflight(crop: CropBox, settings: PlotterSettings) -> CropBox:
    settings.validate()
    bounds = plot_bounds_for_crop(crop, settings).normalized()
    margin = max(0.0, (settings.bounding_box_repeat - 1) * settings.bounding_box_offset)
    return CropBox(
        xmin=bounds.xmin - margin,
        ymin=bounds.ymin - margin,
        xmax=bounds.xmax + margin,
        ymax=bounds.ymax + margin,
    )


def _crop_outline_strokes(crop: CropBox, settings: PlotterSettings) -> list[Stroke]:
    settings.validate()
    box = plot_bounds_for_crop(crop, settings).normalized()
    if box.width <= 0.0 or box.height <= 0.0:
        return []
    return [
        _box_outline_stroke(_expand_box(box, index * settings.bounding_box_offset))
        for index in range(settings.bounding_box_repeat)
    ]


def _expand_box(box: CropBox, offset: float) -> CropBox:
    return CropBox(
        xmin=box.xmin - offset,
        ymin=box.ymin - offset,
        xmax=box.xmax + offset,
        ymax=box.ymax + offset,
    )


def _box_outline_stroke(box: CropBox) -> Stroke:
    return [
        (box.xmin, box.ymin),
        (box.xmax, box.ymin),
        (box.xmax, box.ymax),
        (box.xmin, box.ymax),
        (box.xmin, box.ymin),
    ]


def _fmt(value: float) -> str:
    text = f"{value:.3f}".rstrip("0").rstrip(".")
    return text if text else "0"
