from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from math import hypot
from pathlib import Path

from .geometry import Stroke, plot_bounds_for_crop, total_path_length
from .printer import load_printer_profile
from .settings import CropBox, PlotterSettings


BOUNDING_BOX_DASH_MM = 5.0
BOUNDING_BOX_GAP_MM = 5.0


@dataclass
class GCodeSummary:
    output_path: Path
    stroke_count: int
    segment_count: int
    travel_count: int
    plot_bounds: CropBox
    draw_length_mm: float


def generate_gcode(
    source_path: Path,
    strokes: list[Stroke],
    crop: CropBox,
    settings: PlotterSettings,
    output_path: Path,
) -> GCodeSummary:
    settings.validate()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    pen_down_z = settings.home_z
    pen_up_z = settings.home_z + settings.z_hop
    safe_z = settings.home_z + settings.z_safe_height
    z_move_rate = _gcode_rate_from_speed(settings.travel_speed)
    travel_rate = _gcode_rate_from_speed(settings.travel_speed)
    draw_rate = _gcode_rate_from_speed(settings.draw_speed)
    travel_count = 0
    crop_outline_box = bounding_box_vertex_box(crop, settings)
    crop_outline_boxes = bounding_box_outline_boxes(crop, settings)
    crop_outline_rate = _gcode_rate_from_speed(settings.bounding_box_speed)
    printer = load_printer_profile(settings.device_id)

    lines.extend(
        [
            ";FLAVOR:Marlin",
            "; Generated by Open Pen Slicer",
            f"; Source: {source_path.name}",
            f"; Generated: {datetime.now().isoformat(timespec='seconds')}",
            "; Target: Creality Ender-3 Pro pen plotter",
            "; No extrusion. No hotend or bed heating.",
            "G21 ; set units to millimeters",
            "G90 ; absolute positioning",
            "M104 S0 ; ensure hotend is off",
            "M140 S0 ; ensure bed is off",
            "M107 ; fan off",
            "G28 ; home all axes",
            f"G0 Z{_fmt(safe_z)} F{_fmt(z_move_rate)} ; safe Z before plotting",
        ]
    )

    if crop_outline_box:
        travel_count += _append_box_vertices(
            lines=lines,
            box=crop_outline_box,
            label="Selected crop box vertices",
            pen_down_z=pen_down_z,
            pen_up_z=pen_up_z,
            first_travel_z=safe_z,
            travel_rate=travel_rate,
            z_move_rate=z_move_rate,
        )
    for pass_index, crop_outline_box in enumerate(crop_outline_boxes, start=1):
        offset = pass_index * settings.bounding_box_offset
        travel_count += _append_dotted_box(
            lines=lines,
            box=crop_outline_box,
            label=(
                "Selected dotted padded crop box outline "
                f"{pass_index}/{settings.bounding_box_repeat} "
                f"(+{_fmt(offset)} mm)"
            ),
            pen_down_z=pen_down_z,
            pen_up_z=pen_up_z,
            first_travel_z=pen_up_z,
            travel_rate=travel_rate,
            draw_rate=crop_outline_rate,
            z_move_rate=z_move_rate,
        )
    if crop_outline_box:
        lines.append(f"G0 Z{_fmt(pen_up_z)} F{_fmt(z_move_rate)} ; pen up after crop bounds")

    for index, stroke in enumerate(strokes, start=1):
        if len(stroke) < 2:
            continue
        start = stroke[0]
        travel_count += 1
        lines.extend(
            [
                f"; Stroke {index}",
                f"G0 Z{_fmt(pen_up_z)} F{_fmt(z_move_rate)}",
                f"G0 X{_fmt(start[0])} Y{_fmt(start[1])} F{_fmt(travel_rate)}",
                f"G1 Z{_fmt(pen_down_z)} F{_fmt(z_move_rate)} ; pen down",
            ]
        )
        for x, y in stroke[1:]:
            lines.append(
                f"G1 X{_fmt(x)} Y{_fmt(y)} F{_fmt(draw_rate)}"
            )

    lines.extend(
        [
            f"G0 Z{_fmt(safe_z)} F{_fmt(z_move_rate)} ; safe Z before present move",
            f"G0 X0 Y{_fmt(printer.boundary_y)} F{_fmt(travel_rate)} ; move to top left",
            "M104 S0 ; hotend off",
            "M140 S0 ; bed off",
            "M107 ; fan off",
            "M84 ; disable steppers",
            "; End of Open Pen Slicer G-code",
            "",
        ]
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")

    return GCodeSummary(
        output_path=output_path,
        stroke_count=len(strokes),
        segment_count=sum(max(0, len(stroke) - 1) for stroke in strokes),
        travel_count=travel_count,
        plot_bounds=plot_bounds_including_preflight(crop, settings),
        draw_length_mm=total_path_length(strokes),
    )


def _append_dotted_box(
    lines: list[str],
    box: CropBox,
    label: str,
    pen_down_z: float,
    pen_up_z: float,
    first_travel_z: float,
    travel_rate: float,
    draw_rate: float,
    z_move_rate: float,
) -> int:
    dashes = _dotted_outline_strokes(box)
    if not dashes:
        return 0

    lines.append(
        f"; {label} ({_fmt(BOUNDING_BOX_DASH_MM)} mm dash, "
        f"{_fmt(BOUNDING_BOX_GAP_MM)} mm hop gap)"
    )
    travel_count = 0
    for dash_index, dash in enumerate(dashes):
        start = dash[0]
        lift_z = first_travel_z if dash_index == 0 else pen_up_z
        lines.extend(
            [
                f"G0 Z{_fmt(lift_z)} F{_fmt(z_move_rate)}",
                f"G0 X{_fmt(start[0])} Y{_fmt(start[1])} F{_fmt(travel_rate)}",
                f"G1 Z{_fmt(pen_down_z)} F{_fmt(z_move_rate)} ; pen down",
            ]
        )
        travel_count += 1
        for x, y in dash[1:]:
            lines.append(f"G1 X{_fmt(x)} Y{_fmt(y)} F{_fmt(draw_rate)}")
        lines.append(f"G0 Z{_fmt(pen_up_z)} F{_fmt(z_move_rate)} ; hop gap")
    return travel_count


def _append_box_vertices(
    lines: list[str],
    box: CropBox,
    label: str,
    pen_down_z: float,
    pen_up_z: float,
    first_travel_z: float,
    travel_rate: float,
    z_move_rate: float,
) -> int:
    corners = _box_corners(box)
    if not corners:
        return 0

    lines.append(f"; {label}")
    for corner_index, corner in enumerate(corners):
        lift_z = first_travel_z if corner_index == 0 else pen_up_z
        lines.extend(
            [
                f"G0 Z{_fmt(lift_z)} F{_fmt(z_move_rate)}",
                f"G0 X{_fmt(corner[0])} Y{_fmt(corner[1])} F{_fmt(travel_rate)}",
                f"G1 Z{_fmt(pen_down_z)} F{_fmt(z_move_rate)} ; mark vertex",
                f"G0 Z{_fmt(pen_up_z)} F{_fmt(z_move_rate)} ; pen up after vertex",
            ]
        )
    return len(corners)


def plot_bounds_including_preflight(crop: CropBox, settings: PlotterSettings) -> CropBox:
    settings.validate()
    bounds = plot_bounds_for_crop(crop, settings).normalized()
    margin = max(0.0, settings.bounding_box_repeat * settings.bounding_box_offset)
    return CropBox(
        xmin=bounds.xmin - margin,
        ymin=bounds.ymin - margin,
        xmax=bounds.xmax + margin,
        ymax=bounds.ymax + margin,
    )


def bounding_box_vertex_box(crop: CropBox, settings: PlotterSettings) -> CropBox | None:
    return _crop_outline_box(crop, settings)


def bounding_box_outline_boxes(crop: CropBox, settings: PlotterSettings) -> list[CropBox]:
    box = _crop_outline_box(crop, settings)
    if box is None or settings.bounding_box_repeat <= 0:
        return []
    return [
        _expand_box(box, index * settings.bounding_box_offset)
        for index in range(1, settings.bounding_box_repeat + 1)
    ]


def bounding_box_dotted_strokes(crop: CropBox, settings: PlotterSettings) -> list[Stroke]:
    strokes: list[Stroke] = []
    for box in bounding_box_outline_boxes(crop, settings):
        strokes.extend(_dotted_outline_strokes(box))
    return strokes


def _crop_outline_box(crop: CropBox, settings: PlotterSettings) -> CropBox | None:
    settings.validate()
    box = plot_bounds_for_crop(crop, settings).normalized()
    if box.width <= 0.0 or box.height <= 0.0:
        return None
    return box


def _crop_outline_boxes(crop: CropBox, settings: PlotterSettings) -> list[CropBox]:
    return bounding_box_outline_boxes(crop, settings)


def _expand_box(box: CropBox, offset: float) -> CropBox:
    return CropBox(
        xmin=box.xmin - offset,
        ymin=box.ymin - offset,
        xmax=box.xmax + offset,
        ymax=box.ymax + offset,
    )


def _box_outline_stroke(box: CropBox) -> Stroke:
    return [
        (box.xmin, box.ymin),
        (box.xmax, box.ymin),
        (box.xmax, box.ymax),
        (box.xmin, box.ymax),
        (box.xmin, box.ymin),
    ]


def _box_corners(box: CropBox) -> Stroke:
    box = box.normalized()
    return [
        (box.xmin, box.ymin),
        (box.xmax, box.ymin),
        (box.xmax, box.ymax),
        (box.xmin, box.ymax),
    ]


def _dotted_outline_strokes(box: CropBox) -> list[Stroke]:
    outline = _box_outline_stroke(box.normalized())
    dashes: list[Stroke] = []
    drawing = True
    pattern_remaining = BOUNDING_BOX_DASH_MM
    active_dash: Stroke | None = None

    for start, end in zip(outline, outline[1:]):
        sx, sy = start
        ex, ey = end
        edge_length = hypot(ex - sx, ey - sy)
        if edge_length <= 1e-9:
            continue

        edge_position = 0.0
        cursor = start
        while edge_position < edge_length - 1e-9:
            step = min(pattern_remaining, edge_length - edge_position)
            next_position = edge_position + step
            ratio = next_position / edge_length
            next_point = (sx + (ex - sx) * ratio, sy + (ey - sy) * ratio)

            if drawing:
                if active_dash is None:
                    active_dash = [cursor]
                active_dash.append(next_point)

            cursor = next_point
            edge_position = next_position
            pattern_remaining -= step

            if pattern_remaining <= 1e-9:
                if drawing and active_dash and len(active_dash) >= 2:
                    dashes.append(active_dash)
                    active_dash = None
                drawing = not drawing
                pattern_remaining = (
                    BOUNDING_BOX_DASH_MM if drawing else BOUNDING_BOX_GAP_MM
                )

    if active_dash and len(active_dash) >= 2:
        dashes.append(active_dash)
    return dashes


def _fmt(value: float) -> str:
    text = f"{value:.3f}".rstrip("0").rstrip(".")
    return text if text else "0"


def _gcode_rate_from_speed(speed_mm_s: float) -> float:
    return speed_mm_s * 60.0
