device_id: CE3PRO
rotation_quarters: 3
bounding_box_repeat: 2
bounding_box_offset: 0.5
bounding_box_speed: 50.0
curve_tolerance: 0.35
target_directory: Downloads
clear_before_write: true
eject_after_write: true
