active_file: raw/raipal-mech_pen-plot_FORE.DXF
device_id: CE3PRO
origin_x: 76.98
origin_y: 28.73
scale: 1.4
rotation_quarters: 0
bounding_box_repeat: 2
bounding_box_offset: 2.0
bounding_box_speed: 25.0
curve_tolerance: 0.35
target_directory: Downloads
output_filename: '[pen_plotter] raipal-mech_pen-plot_FORE.gcode'
crop:
  xmin: 115.8239020668
  ymin: 61.10875447693334
  xmax: 178.8472981144029
  ymax: 149.2061750741
