
name: "Creality Ender 3 Pro Test"

home:
  x: 38.0
  y: 21.0
  z: 12.2

z_height:
  hop : 0.5
  safe: 5.0

speed:
  draw  : 50.0
  travel: 150.016667

boundary:
  x: 235.0
  y: 235.0
  z: 250.0

safety_margin: 5.0
